# Generated by Django 4.2.7 on 2023-11-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, choices=[('EMPLOYER', 'Employer'), ('CANDIDATE', 'Candidate')], default='CANDIDATE'),
        ),
    ]
