# Generated by Django 4.2.7 on 2023-11-16 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, default=5)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='candidate/profile_images/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='candidate/banner_images/')),
                ('employer_followers', models.IntegerField(blank=True, default=0)),
                ('employer_description', models.TextField(blank=True, null=True)),
                ('employer_avarage_salary', models.IntegerField(blank=True, default=500000)),
                ('employer_head_quarters', models.CharField(blank=True, null=True)),
                ('candidate_following', models.IntegerField(default=0, null=True)),
                ('candidate_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_date_of_birth', models.DateField(blank=True, null=True)),
                ('candidate_resume', models.FileField(blank=True, null=True, upload_to='candidate/resumes/')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
