# Generated by Django 4.2.7 on 2023-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_address_profile_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='candidate_expecting_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
