# Generated by Django 4.2.7 on 2023-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_candidate_expecting_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
