# Generated by Django 4.2.7 on 2023-12-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_phone_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='candidate_experience_month',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='candidate_experience_year',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='candidate_skills',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
