# Generated by Django 4.2.7 on 2023-11-23 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.CharField(blank=True, max_length=255, null=True)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_ctc', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, default=0)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('work_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vaccancy', models.IntegerField(blank=True, default=1)),
                ('skills', models.CharField(blank=True, max_length=300, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('job_id', models.CharField(blank=True, max_length=255)),
                ('application_count', models.IntegerField(blank=True, default=0, null=True)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('highlight', models.TextField(blank=True, null=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
