# Generated by Django 4.2.7 on 2023-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
