# Generated by Django 4.2.7 on 2023-12-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proffessional', '0002_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='cource_type',
            new_name='course_type',
        ),
    ]
