# Generated by Django 4.2.7 on 2023-11-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_description', models.TextField(blank=True, null=True)),
                ('employer_location', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.IntegerField(blank=True, default=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('avarage_salary', models.IntegerField(blank=True, default=500000)),
                ('role', models.CharField(default='Employer')),
                ('head_quarters', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('followers', models.IntegerField(blank=True, default=0)),
                ('employer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
