# Generated by Django 4.2.7 on 2023-11-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='employer/banner_images/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='employer/profile_images/'),
        ),
    ]
